DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS LIBRARIES;
DROP TABLE IF EXISTS BOOKS;
DROP TABLE IF EXISTS GENRE_BOOKS;
DROP TABLE IF EXISTS GENRES;

CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE LIBRARIES (
  ID SERIAL PRIMARY KEY NOT NULL,
  USER_ID INT REFERENCES USERS(ID) ON DELETE CASCADE,
  NAME VARCHAR(255) NOT NULL,
  PUBLIC BOOLEAN NOT NULL
);

CREATE TABLE BOOKS (
  ID SERIAL PRIMARY KEY NOT NULL,
  LIBRARY_ID INT REFERENCES LIBRARIES(ID) ON DELETE CASCADE,
  NAME VARCHAR(255) NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  RATING INT NOT NULL,
  NOTES VARCHAR(1000) NOT NULL,
  OWNERSHIP BOOLEAN NOT NULL
);

CREATE TABLE GENRE_BOOKS (
  BOOK_ID INT REFERENCES BOOKS(ID) ON DELETE CASCADE,
  GENRE_ID INT REFERENCES GENRES(ID) ON DELETE CASCADE
);

CREATE TABLE GENRES (
  ID SERIAL PRIMARY KEY NOT NULL,
  NAME VARCHAR(255) NOT NULL
);
